### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Vili1** [HackerHansen/AmongUsCosmetics#2]
i couldnt find a way to contact u, i wanted to ask if its okay to implement ur work in my project https://github.com/Vili1/Among-us-Free-Chat-unlocker i will credit u ofc

**Comment by HackerHansen** [comment]
> i couldnt find a way to contact u, i wanted to ask if its okay to implement ur work in my project https://github.com/Vili1/Among-us-Free-Chat-unlocker i will credit u ofc

Yeah for sure

**Comment by HackerHansen** [comment]
Oh and also just fyi there's an issue with the signature scan function (I'll fix it later)

**Comment by Vili1** [comment]
no need i will just steal the sigs lol ofc will give u credit
