### ISSUE TITLE
Doesn't work with the last version

### ISSUE THREAD

**Issue by Pafa8814** [HackerHansen/AmongUsCosmetics#3]
The cosmetics system was changed with the latest Among Us update (v2022.3.29). I tried to find the necessary files in the new version myself, but I failed. Please, if you have the opportunity and time, update your application for the new version. Thank you!

**Comment by HackerHansen** [comment]
> The cosmetics system was changed with the latest Among Us update (v2022.3.29). I tried to find the necessary files in the new version myself, but I failed. Please, if you have the opportunity and time, update your application for the new version. Thank you!

Alright, thanks for letting me know. I'll look into it.

**Comment by HackerHansen** [comment]
Ok the source is fixed, I haven't made a release with an exe yet though

**Comment by HackerHansen** [comment]
Ok I put the exe in releases, it seems to flag av quite a bit tho

**Comment by StopRussiaNOW** [comment]
yeah it gets flag alot but i managed to stop it

**Comment by Pafa8814** [comment]
@HackerHansen Everything works. Thank you so much!

**Comment by HackerHansen** [comment]
np, I'm glad it works for you now
