### ISSUE TITLE
The Cosmetic Unlocker Still does not work  idk why

### ISSUE THREAD

**Issue by StopRussiaNOW** [HackerHansen/AmongUsCosmetics#4]

**Comment by HackerHansen** [comment]
> _No description provided._

What version of the game are you on, and can you send a screenshot of the exe window?

**Comment by StopRussiaNOW** [comment]
Oh i just realised i was using the exe version

**Comment by HackerHansen** [comment]
I mean you have to be running an exe for it to work but I'm assuming it works for you now

**Comment by StopRussiaNOW** [comment]
i did

**Comment by StopRussiaNOW** [comment]
i was running it

**Comment by StopRussiaNOW** [comment]
but everything is failin
![Screenshot (37)](https://user-images.githubusercontent.com/100543254/161361906-ae2670a8-2c9f-49d0-821b-ce61f4164142.png)
g

**Comment by StopRussiaNOW** [comment]
i was running it but still does not work here is a screenshot of whats happening
![Screenshot (39)](https://user-images.githubusercontent.com/100543254/161361971-b8fa5313-0174-4560-91b5-a99e52701bd0.png)

**Comment by HackerHansen** [comment]
> i was running it but still does not work here is a screenshot of whats happening ![Screenshot (39)](https://user-images.githubusercontent.com/100543254/161361971-b8fa5313-0174-4560-91b5-a99e52701bd0.png)

You have to actually download the new version to use it. The one you have open is the old one

**Comment by StopRussiaNOW** [comment]
can you send me the link for the new version

**Comment by HackerHansen** [comment]
> can you send me the link for the new version

Check releases

**Comment by StopRussiaNOW** [comment]
i did but it still does not work i think the download is not working i use the exe version you might have to update the download for exe

**Comment by HackerHansen** [comment]
> i did but it still does not work i think the download is not working i use the exe version you might have to update the download for exe

Oh bruh you're right, I think I accidentally uploaded the wrong exe 😅 

I'll fix it rn

**Comment by HackerHansen** [comment]
Sorry for the inconvenience, I had a 0 iq moment and accidentally clicked the wrong folder

**Comment by HackerHansen** [comment]
Ok I uploaded the new one, try it and let me know if it works for you lol
