### ISSUE TITLE
Very good

### ISSUE THREAD

**Issue by tedomedo** [HackerHansen/AmongUsCosmetics#5]
"Very good " is meant for your Cosmetics Unlocker.CETRAINER. But your .exe doesn't work. I got message that this program can't work in my pc which is windows 10 64b. Create CETRAINER for v2022.3.29 too.

**Comment by HackerHansen** [comment]
> "Very good " is meant for your Cosmetics Unlocker.CETRAINER. But your .exe doesn't work. I got message that this program can't work in my pc which is windows 10 64b. Create CETRAINER for v2022.3.29 too.

Can you screenshot the message telling you it doesn't work?

**Comment by tedomedo** [comment]
Instantly after download is completed, i see warning from Defender that this file is virus Trojan:Win32/Sabsik.FL.A!ml. I renewed it from quarantine but maybe something from exe was deleted. When i run exe, i see this: 
![slika](https://user-images.githubusercontent.com/52840688/162159893-d9c69127-7d24-42fb-a238-c2bff7e13a6a.png)
It's in my language, This is translation from google translate: "This application does not work on your computer. Contact your software publisher for the version of the program for your personal computer."
Because this doesn't work, I use Among US v2021 november and use your Cosmetics Unlocker.CETRAINER. Can you create a CETRAINER to change name too?

**Comment by HackerHansen** [comment]
> Instantly after download is completed, i see warning from Defender that this file is virus Trojan:Win32/Sabsik.FL.A!ml. I renewed it from quarantine but maybe something from exe was deleted. When i run exe, i see this: ![slika](https://user-images.githubusercontent.com/52840688/162159893-d9c69127-7d24-42fb-a238-c2bff7e13a6a.png) It's in my language, This is translation from google translate: "This application does not work on your computer. Contact your software publisher for the version of the program for your personal computer." Because this doesn't work, I use Among US v2021 november and use your Cosmetics Unlocker.CETRAINER. Can you create a CETRAINER to change name too? As guest i have to use random name.

Oops, sorry for the late reply, I forgot about this issue lol 

I don't plan on making a cetrainer for this, but from the screenshot it looks like the program's size is 0 kb. Try downloading it again and see if that works

**Comment by HackerHansen** [comment]
Closing this as a stale for now
