### ISSUE TITLE
All pets and skins go away after closing and opening Among Us

### ISSUE THREAD

**Issue by Calculator2308** [HackerHansen/AmongUsCosmetics#6]
I have to boot up the exe file every time I want to play Among Us. Is there any way to have the program automatically boot up when I open Among Us?

**Comment by HackerHansen** [comment]
> I have to boot up the exe file every time I want to play Among Us. Is there any way to have the program automatically boot up when I open Among Us?

Hi, sorry for the late reply, I didn't notice this issue until now. 

You can just leave the exe open and it should auto attach each time you open the game, you don't need to close and reopen it each time.
