### ISSUE TITLE
GameAssembly Not Loading

### ISSUE THREAD

**Issue by zeldaking** [HackerHansen/AmongUsCosmetics#7]
![image](https://user-images.githubusercontent.com/43257330/164115917-d294ee41-fd51-40c4-8185-ad796677c715.png)
Heres my problem pls help.

**Comment by HackerHansen** [comment]
> ![image](https://user-images.githubusercontent.com/43257330/164115917-d294ee41-fd51-40c4-8185-ad796677c715.png) Heres my problem pls help.

Hi, are you using the game version from Steam? If not, which version are you using?

**Comment by HackerHansen** [comment]
Closing this for now as a stale, feel free to reopen if you still have issues

**Comment by zeldaking** [comment]
Im using Among Us from the PC Xbox Game Pass.

**Comment by HackerHansen** [comment]
> 

Oh ok, I don't own that version so I can't fix it right now, sorry. I'll update the README thingy to say that it only works on the Steam version tho
