### ISSUE TITLE
Similar game

### ISSUE THREAD

**Issue by wixarsceath** [HackerHansen/AmongUsCosmetics#8]
Hey! It's not an issue, just thought you might be interested in doing something similar for another game? It's called Goose Goose Duck

**Comment by HackerHansen** [comment]
Thanks for the suggestion, but I only made the Among Us thingy because I used to play with friends a lot. I don't really play Goose Goose Duck that much at the time being, but if I ever become interested in making something similar for that game then I'll let you know.
