### ISSUE TITLE
Not an issue...

### ISSUE THREAD

**Issue by aphoninaalina** [HackerHansen/AmongUsCosmetics#9]
Hey! Sorry to write here, I don't know any other ways... I want to do something similar for another game, but I'm new to Cheat Engine. Could you please explain to me how you found the signature of the locked and unlocked cosmetics?

Thank you!

**Comment by HackerHansen** [comment]
Hi, sorry for the late response. 

There are functions that check if a cosmetic is unlocked, you can find them with tools such as https://github.com/Perfare/Il2CppDumper or just by debugging (although the former method requires a lot less effort and is preferred). 

Once you get to the right function, you can just force it to return 1. In my program I just skip the je so it always returns 1, but it's also possible to just set eax to 1 and ret immediately at the start of the function. 

Hope this helps

**Comment by aphoninaalina** [comment]
Hey! Thank you so much for the answer! I didn't succeed in everything, but I'm not giving up! 

Tried to apply it to Among Us. If I understand correctly, the Check For New Unlockables functions are responsible for cosmetics. But the forced return to true didn't work... Perhaps something has changed in the latest version of the game? Or could it be related to something else? Please tell me if you know anything about it

Thank you and have a nice day!

**Comment by HackerHansen** [comment]
You have the wrong function. Try searching "GetUnlocked" (although there are a lot of these that aren't related to cosmetics)

**Comment by aphoninaalina** [comment]
Hey! Thanks for the reply!

As far as I understand, the function that your program changes is outside GameAssembly.dll. Could you share how you found it? And, perhaps you know, or could you guess, is there such a mechanism for unlocking cosmetics in all such games, or is it worth paying attention to other things?

Have a nice day!

**Comment by HackerHansen** [comment]
The function I'm changing is inside gameassembly.dll and I found it with il2cppdumper. Try unlocking just hats or just pets first, one category at a time.

For other games, this will only work if the cosmetics check is client side. If the server is checking if you actually own the cosmetics then either the cosmetics will only show up on your screen or it just won't work
